# Generated by Django 5.2.7 on 2025-10-26 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('iduser', models.AutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('isbanned', models.IntegerField(db_column='isBanned')),
                ('isactive', models.IntegerField(db_column='isActive')),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('idnotice', models.AutoField(db_column='idNotice', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('subject', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
                ('description', models.TextField(blank=True, null=True)),
                ('attachment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('idtag', models.AutoField(db_column='idTag', primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'tag',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('iduser', models.OneToOneField(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shared_app.myuser')),
            ],
            options={
                'db_table': 'admin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('iduser', models.OneToOneField(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shared_app.myuser')),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('dateofbirth', models.DateField(blank=True, db_column='dateOfBirth', null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('iduser', models.OneToOneField(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shared_app.myuser')),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('dateofbirth', models.DateField(blank=True, db_column='dateOfBirth', null=True)),
                ('isverified', models.IntegerField(db_column='isVerified')),
            ],
            options={
                'db_table': 'tutor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('idcollaboration', models.AutoField(db_column='idCollaboration', primary_key=True, serialize=False)),
                ('datebegin', models.DateField(db_column='dateBegin')),
                ('dateend', models.DateField(blank=True, db_column='dateEnd', null=True)),
                ('idnotice', models.ForeignKey(db_column='idNotice', on_delete=django.db.models.deletion.CASCADE, to='shared_app.notice')),
                ('idstudent', models.ForeignKey(db_column='idStudent', on_delete=django.db.models.deletion.CASCADE, to='shared_app.student')),
                ('idtutor', models.ForeignKey(db_column='idTutor', on_delete=django.db.models.deletion.CASCADE, to='shared_app.tutor')),
            ],
            options={
                'db_table': 'collaboration',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('idrating', models.AutoField(db_column='idRating', primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('idcollaboration', models.ForeignKey(db_column='idCollaboration', on_delete=django.db.models.deletion.CASCADE, to='shared_app.collaboration')),
                ('idrateduser', models.ForeignKey(db_column='idRatedUser', on_delete=django.db.models.deletion.CASCADE, related_name='rating_idrateduser_set', to='shared_app.myuser')),
                ('idratinguser', models.ForeignKey(db_column='idRatingUser', on_delete=django.db.models.deletion.CASCADE, to='shared_app.myuser')),
            ],
            options={
                'db_table': 'rating',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Applied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnotice', models.ForeignKey(db_column='idNotice', on_delete=django.db.models.deletion.CASCADE, to='shared_app.notice')),
                ('idtag', models.ForeignKey(db_column='idTag', on_delete=django.db.models.deletion.CASCADE, to='shared_app.tag')),
            ],
            options={
                'db_table': 'applied',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='notice',
            name='idpublisher',
            field=models.ForeignKey(db_column='idPublisher', on_delete=django.db.models.deletion.DO_NOTHING, to='shared_app.student'),
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('idver', models.AutoField(db_column='idVer', primary_key=True, serialize=False)),
                ('iduser', models.OneToOneField(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, to='shared_app.tutor')),
            ],
            options={
                'db_table': 'verification',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('idrequest', models.AutoField(db_column='idRequest', primary_key=True, serialize=False)),
                ('isaccepted', models.CharField(db_column='isAccepted', max_length=1)),
                ('idnotice', models.ForeignKey(db_column='idNotice', on_delete=django.db.models.deletion.CASCADE, to='shared_app.notice')),
                ('idtutor', models.ForeignKey(db_column='idTutor', db_comment="isAccepted possible values - 'P' as in 'Pending', 'A' as in 'Accepted', 'R' as in 'Rejected'", on_delete=django.db.models.deletion.CASCADE, to='shared_app.tutor')),
            ],
            options={
                'db_table': 'request',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='notice',
            name='idtutor',
            field=models.ForeignKey(blank=True, db_column='idTutor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_app.tutor'),
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('idcv', models.AutoField(db_column='idCV', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('picture', models.TextField(blank=True, null=True)),
                ('aboutme', models.TextField(blank=True, db_column='aboutMe', null=True)),
                ('education', models.TextField()),
                ('projects', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('idtutor', models.OneToOneField(db_column='idTutor', on_delete=django.db.models.deletion.CASCADE, to='shared_app.tutor')),
            ],
            options={
                'db_table': 'cv',
                'managed': True,
            },
        ),
    ]
