# Generated by Django 5.2.7 on 2025-10-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='picture',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
